**Уровень 0**:  
Создайте матрицу 3 на 3, заполненную числами от 1 до 9  
Прибавьте к ней матрицу с единицами на диагонале  
Умножьте полученную матрицу на вектор (1, 2, 3)  
Посчитайте обратную матрицу к полученной матрице

In [1]:
import numpy as np

In [2]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
MI = np.eye(3)
MI

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
Msum = M + MI
Msum

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [5]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [6]:
Mprod = Msum @ v
# или так
# Mprod = np.dot(Msum, v)
Mprod

array([15., 34., 53.])

Мы получили вектор. Обратная матрица существует только для квадратной матрицы, но никак не для вектора.

In [7]:
# Соответственно, данный шаг теряет всякий смысл и выдает ошибку
# np.linalg.inv(Mprod)

Посчитаем обратную матрицу для матрицы Msum

In [10]:
MsumInv = np.linalg.inv(Msum)

Проверим, получается ли единичная матрица при перемножении Msum и MsumInv

In [11]:
Msum @ MsumInv

array([[ 1.00000000e+00, -2.22044605e-16,  4.44089210e-16],
       [-1.77635684e-15,  1.00000000e+00,  8.88178420e-16],
       [-1.77635684e-15,  4.44089210e-16,  1.00000000e+00]])

Проверка успешно пройдена