**Уровень 0**  
Придумайте матрицы, которые обладают следующими свойствами:  
a) диагональная, ортогональная, но не единичная(!):  
b) верхнетреугольная, ортогональная:  
c) нижнетреугольная, ортогональная:  
d) матрица, у которой определитель = 1, и все элементы не равны 0:  
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!  

Найдите собственные значения и собственные вектора матриц:  
m = np.array([[2, 2],  
[1, 3]])  
print(m)  

In [1]:
import numpy as np

a) диагональная, ортогональная, но не единичная(!):

In [2]:
A = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])
A

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [3]:
AT = A.T
AT

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

Проверяем матрицу А на ортогональность путем умножения ее на транспонированную к ней матрицу

In [4]:
A @ AT

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Матрица А:  
- диагональная (все элементы, кроме элементов главной диагонали равны 0);  
- прошла проверку на ортогональность (A * AT = единичной м.);  
- не единичная (-1 уже не 1).

b) верхнетреугольная, ортогональная  
она же  
c) нижнетреугольная, ортогональная

In [5]:
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
BT = B.T
BT

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
B @ BT

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Во всех других случаях матрица 3х3 либо не верхне-/нижнетреугольная, либо не ортогональная

d) матрица, у которой определитель = 1, и все элементы не равны 0:

In [8]:
D = np.array([[7, 4], [5, 3]])
D

array([[7, 4],
       [5, 3]])

In [9]:
det = np.linalg.det(D)
det

0.9999999999999996

Найдите собственные значения и собственные вектора матриц:

In [10]:
m = np.array([[2, 2], [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [11]:
w, v = np.linalg.eig(m)
for i in range(len(w)):
    print(f'Собственному значению {str(w[i])} соответствует собственный вектор {str(v[:,i])}')

Собственному значению 1.0 соответствует собственный вектор [-0.89442719  0.4472136 ]
Собственному значению 4.0 соответствует собственный вектор [-0.70710678 -0.70710678]
